version: "3.8"

services:
  app:
    container_name: stac_generator
    build:
      context: .
      dockerfile: .docker/Dockerfile
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
      - /mnt/:/mnt/
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  redis_data:
